version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - database
    restart: on-failure
    command: python manage.py runserver localhost:8000
    container_name: server

  database:
    image: postgres:14.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    container_name: postgres_db
    ports:
      - 5432:5433