build:
	docker-compose build

up:
	docker-compose up -d

down:
	docker-compose down

show-logs:
	docker-compose logs

makemigrations:
	docker-compose exec api python manage.py makemigrations

migrate:
	docker-compose exec api python manage.py migrate

createsuperuser:
	docker-compose exec api python manage.py createsuperuser

