# Generated by Django 4.2.2 on 2023-06-25 11:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationState',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('DIRTY', 'DIRTY'), ('DURING', 'DURING'), ('READY', 'READY'), ('FAILED', 'FAILED')], default='DIRTY', max_length=10)),
                ('method', models.CharField(choices=[('EMAIL', 'EMAIL'), ('PHONE', 'PHONE')], max_length=10)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='states', to='contacts.contact')),
                ('notification_template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='states', to='notifications.notificationtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
