# Generated by Django 4.2.2 on 2023-06-27 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('notifications', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationstate',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='notificationstate',
            name='notification_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='notifications.notificationtemplate'),
        ),
    ]
