# Generated by Django 4.2.2 on 2023-07-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsession',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
