# Generated by Django 4.2.2 on 2023-07-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_notificationsession_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
