# Generated by Django 4.2.2 on 2023-07-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_notificationsession_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsession',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
