# Generated by Django 4.2.2 on 2023-07-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_notificationstate_notification_template_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationstate',
            old_name='noticication_session',
            new_name='notification_session',
        ),
    ]
