# Generated by Django 4.2.2 on 2023-07-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_notificationsession_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsession',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
